### PR TITLE
Add iOS Framework target

### LINKED ISSUE #202: Carthage compatibility
Would you be interested in a Pull Request that added a Framework target for iOS and made sure that SBJSON was building nicely with [Carthage](https://github.com/Carthage/Carthage)?

This wouldn't negatively affect the CocoaPods integration, which seems to be the currently recommended way of doing things.

### PR DESCRIPTION
**Pull request by robb**
As mentioned in #202, this is more or less the MVP version of adding Carthage compatibility.

- [x] Add a _SBJson-iOS_ target
- [x] Make the Mac and iOS target more similar

I've confirmed that the project still validates by pulling in the [`podspec`](https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/SBJson/4.0.2/SBJson.podspec.json) and running `pod lib lint SBJson.podspec.json` locally.

Note that while the targets are called _SBJson-Mac_ and _SBJson-iOS_, the resulting frameworks are both called `SBJson.framework`.

Optionally, we could remove the static library target, as CocoaPods will create a new one regardless, this would also allow simplifying the project structure (i.e. moving files from `src/main` to `SBJson` and from `src/test` to `SBJsonTests` which is how Xcode would set up a new project). Let me know how you'd like it done.

It also may make sense to run `carthage build --no-skip-current` as part of CI to make sure the project remains Carthage compatible in the future.

Fixes #202

### CODE REVIEW

**Comment by stig** [comment]
I'm open to more unification, in theory. The whole src/ thing is really annoying. I just don't know how I can run the tests for iOS AND Mac targets without the separate targets. And I don't want one target grabbing all the source files from the other target's directory either... so this is the best I've managed.

**Comment by stig** [comment]
Happy to run carthage as part of the travis build; just make it part of the pull request.

**Comment by robb** [comment]
> And I don't want one target grabbing all the source files from the other target's directory either... so this is the best I've managed.

What's so bad about it? In e.g. [Mantle](http://github.com/Mantle/Mantle/) we have e.g. `MantleTests/MTLArrayManipulationSpec.m` be part of both the _Mantle-MacTests_ and _Mantle-iOSTests_ targets and it works well.

**Comment by stig** [comment]
>> And I don't want one target grabbing all the source files from the other target's directory either... so this is the best I've managed.

> What's so bad about it? In e.g. Mantle we have e.g. MantleTests/MTLArrayManipulationSpec.m be part of both the Mantle-MacTests and Mantle-iOSTests targets and it works well.

It's not a big deal, tbh. If it makes things simpler, I'm open to change it.

**Comment by robb** [comment]
I think

```objc
#import <SBJson.h>
#import <SBJson4.h>
```

should still work but it's better to make sure it does. Do you happen to have a project at hand?

**Comment by robb** [comment]
Build's green now :green_apple:

**Comment by robb** [comment]
[Here's an updated `podspec` that passes linting](https://gist.github.com/robb/82f0d924a5a9c99499aa).

**Comment by stig** [comment]
I should have, shouldn't I! I don't remember where though. :-(

Stig

**Comment by stig** [comment]
Great!

What's with the .a.a?

+ BuildableName = "libSBJson.a.a"

**Comment by stig** [comment]
(I have spotty internet connection and am away next week so not sure I get time to review this properly until the week after. Sorry!)

**Comment by robb** [comment]
> What's with the .a.a?

Whoops, addressed.

**Comment by stig** [comment]
It's hard to review with the massive move of files mixed in. Is it possible to do that as a separate pull request? It's not really central to this feature, is it?

**Comment by robb** [comment]
Hmm, could you maybe review the PR locally with `git diff --diff-filter=ADM`?

I'm on my phone so I can't confirm this does what it should but the idea is to ignore renames.

**Comment by stig** [comment]
I will try that. 

Stig

**Comment by stig** [comment]
Hi @robb,

I've attempted to review this but there's just too many things going on here for me to pull it. Let me restate that *I am happy to support Carthage*, but I have some issues with this implementation. Specifically:

- I would prefer the header file to not be renamed, and stay named `SBJson4.h`.
- I would rather the source & test files were not. (If Carthage support cannot be achieved without it I will reconsider, but please do the rename as a separate pull request.)
- I don't want to go the route of an explicit module map; as mentioned above I'd rather see the framework renamed to contain the major version in the name (c.f. libc6, limxml2, etc).
- I am very happy for prefix headers to be removed, but *please submit a separate pull request* for this.
- I am OK to update deployment targets etc.
- If we can manage to update the CI target to run tests for carthage too, that would be ideal. (That being the whole point of the pull to start with.)

I'm sorry I've taken so long to get back to. Hope the above is clear.

**Comment by robb** [comment]
> I would prefer the header file to not be renamed, and stay named `SBJson4.h`.

> I don't want to go the route of an explicit module map; as mentioned above I'd rather see the framework renamed to contain the major version in the name (c.f. libc6, limxml2, etc).

So we're looking at two frameworks named `SBJson4.framework` (with different target names) as well as a single `libSBJson.a` for iOS 7 and lower. Right?

> I would rather the source & test files were not.

I assume you meant "moved around"? It's not necessary at all :ok_hand: 

> I am very happy for prefix headers to be removed, but please submit a separate pull request for this.

See #205

**Comment by stig** [comment]
> 
> I would prefer the header file to not be renamed, and stay named SBJson4.h.
> 
> I don't want to go the route of an explicit module map; as mentioned above I'd rather see the framework renamed to contain the major version in the name (c.f. libc6, limxml2, etc).
> 
> So we're looking at two frameworks named SBJson4.framework (with different target names) as well as a single libSBJson.a for iOS 7 and lower. Right?
> 
With iOS9 already in beta I don’t really see a point of supporting iOS7 and lower. There’s no change in actual code, so they can stick with the previous version.

> I would rather the source & test files were not.
> 
> I assume you meant "moved around"? It's not necessary at all
> 

Yes, that’s what I meant. Sorry for the ambiguity, it was late at night :-)

Stig

**Comment by hotbott** [comment]
Are there any plans to accept the PR?

**Comment by stig** [comment]
@hotbott not in its current state, sorry. I'm keeping this open in case someone is willing to address the comments I made [here](https://github.com/stig/json-framework/pull/203#issuecomment-123073775).

**Comment by stig** [comment]
For information for anyone interested in working on this, and if it was not clear already, any resulting framework should be named SBJson4, i.e. have the 4 as part of the name / classes / headers. This is so that it can be used in the same project as SBJson3 -- since version 4 breaks backwards compatibility.

**Comment by hotbott** [comment]
I'll create a new PR with correct naming.

**Comment by stig** [comment]
A Carthage framework was added in #216

**Pull request closed without merging**
